name: Publish on chrome store

on:
  push:
    branches: [main]
    paths-ignore:
      - "package.json"
      - "src/manifest.json"
      - "CHANGELOG.md"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run a one-line script
        run: yarn && yarn build

      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.GCS_REFRESH_TOKEN }}
          client-id: ${{ secrets.GCS_CLIENT_ID }}
          client-secret: ${{ secrets.GCS_CLIENT_SECRET }}
          file-name: "./build.zip"
          app-id: "oobifkfbojcheinmoejdhgllgennkjpe"
          publish: true

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          version-file: ./src/manifest.json
          skip-on-empty: false
          output-file: "CHANGELOG.md"
