name: Publish on chrome store

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Run a one-line script
        run: yarn && yarn build

      - name: Chrome Extension upload & publish
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: "xxxxxxxxxxxxxxxxxxxxxx"
          client-id: "xxxxxxxxxxxxx"
          client-secret: "xxxxxxxxxxxx"
          file-name: "./build.zip"
          app-id: "xzc12xzc21cx23"
          publish: true
